// Read digest artifacts written by build/digest-builder.ts.
// Astro pages use this at build time to enumerate paths and render content.

import { readFileSync, readdirSync, existsSync, statSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { assignSlugsForDate } from './slug-resolve.ts';
import type { ModalityTag, IntentTag, MethodologyTag } from './tags.ts';
import type { ContentType } from './content-type.ts';

// Detail union (v0.4.0 → v0.4.2):
//   - flat string for single statements
//   - {text, subdetails[]} for 1D nested rows (v0.4.1)
//   - {text, table:{columns, rows}} for 2D matrix comparisons (v0.4.2)
export type DigestTable = { columns: string[]; rows: string[][] };
// v0.26 (Thread 1): a bullet's figure-locked number was read from a figure, not
// the abstract (see llm-pipeline SourceTier). Rendered as a citation mark.
export type SourceTier = 'figure';
export type DigestDetail =
  | string
  | { text: string; subdetails: string[]; source_tier?: SourceTier }
  | { text: string; table: DigestTable; source_tier?: SourceTier }
  | { text: string; source_tier?: SourceTier };

// v0.10: a single promoted figure (image URL + numeric caption or comparison
// table). Studies carry an ordered array of these; see studyFigures().
export type DigestFigure = {
  url: string;
  caption: string | DigestTable | null;
};

// v0.5+: typed source reference. Resolves to bookmarks/papers/slides
// in the rendered page. Older v0.4 artifacts use tweet_ids only.
export type DigestSourceRef =
  | { type: 'tweet'; id: number }
  | { type: 'paper'; id: number }
  | { type: 'slide'; id: number };

export type DigestStudy = {
  name: string;
  tldr: string;
  details: DigestDetail[];
  // v0.10: ordered gallery of promoted figures. Empty/absent when the agent
  // abstained. Use studyFigures() to read — it normalizes the v0.4 single-figure
  // shape (key_figure_url/caption) into this array for old artifacts.
  figures?: DigestFigure[];
  // v0.4: single promoted figure. Both fields are null when the per-study
  // agent abstains or when the post-hoc OCR validator rejects the caption.
  // v0.4.3: caption may also be a DigestTable for comparison-chart figures.
  // Superseded by `figures` in v0.10; retained so old artifacts still render.
  key_figure_url?: string | null;
  key_figure_caption?: string | DigestTable | null;
  nct: string | null;
  // v0.4: synthetic ids. v0.5+ prefers source_ids for typed refs.
  tweet_ids: number[];
  source_ids?: DigestSourceRef[];
  // v0.6+: stable per-study slug. Older artifacts won't have this — renderers
  // should fall back to deriveSlug(name) from src/lib/slug.ts.
  slug?: string;
  // v0.7+ analyst verdict (see VOICE.md "SOC-implication verdict").
  // Optional — older artifacts won't have it.
  verdict?: StudyVerdict;
  // v0.22: perspective-framed "Why it matters" prose. A 2-4 sentence
  // interpretive paragraph generated by Phase 2 under the active
  // DIGEST_PERSPECTIVE lens — the one long-form surface on the card. It
  // surfaces the additive figure/table/results detail the terse bullets drop
  // (subgroup signal, in-field control, dose/fractionation transferability,
  // pattern of failure) and names the decision the study moves for the lens
  // reader. Every number still grounded in source (no-fabrication outranks the
  // lens). Null/absent when the agent abstains (nothing additive beyond the
  // bullets) or on older artifacts. Mirrored in llm-pipeline.ts — keep both in
  // lockstep.
  significance?: string | null;
  // v0.22: display label of the lens that produced `significance`, e.g.
  // "Radiation oncology". Stamped at build time from DIGEST_PERSPECTIVE; drives
  // the "WHY IT MATTERS · {label}" callout heading. Null/absent when no
  // perspective was set (significance then renders under the generic heading)
  // or when there is no significance.
  significance_perspective?: string | null;
  // v0.26 (E3): the "Monday clinic" decision line — one grounded sentence naming
  // which patient this study moves and which it does not. Peer-forward trigger +
  // E1 share-body content. Distinct from significance; abstains when it would
  // repeat it. Mirrored in llm-pipeline.ts:DigestStudy — keep in lockstep.
  monday_clinic?: string | null;
  // v0.14.5 (E5): true when any source is a preprint. Drives the "not
  // peer-reviewed" badge; the verdict was already capped at build. Absent on
  // older artifacts and on non-preprint studies.
  is_preprint?: boolean;
  // v0.8.1: per-study open questions (Phase 2). Older artifacts carry these at
  // the site level (DigestSite.open_questions); renderers fall back to that.
  open_questions?: string[] | null;
  // v0.9: optional CONSORT participant flow (randomized trials only, when the
  // source reports per-arm counts). Rendered as a dropdown diagram on the card.
  consort?: ConsortDiagram | null;
  // v0.10: typed cross-cutting tag fields. The Phase 2 agent picks one value
  // per namespace from the enums in src/lib/tags.ts. Null when the agent
  // can't classify (single-arm phase-1 with no comparator = no modality, etc.)
  // — the study still appears on other landing pages; only that namespace's
  // tag landing skips it. The unified tags[] VIEW is derived at build time
  // from these typed fields + verdict.soc_implication + digest.conference
  // (see src/lib/tag-index.ts).
  modality?: ModalityTag | null;
  intent?: IntentTag | null;
  methodology?: MethodologyTag | null;
  // v0.16: study_report (default) vs review, decided at Phase 1. A review
  // carries no verdict and renders discussed_trials instead of a numbers-first
  // card. Absent === study_report (back-compat with the pre-v0.16 corpus).
  // Mirrored from src/lib/llm-pipeline.ts:DigestStudy — keep both in lockstep.
  content_type?: ContentType;
  // v0.16: trial acronyms a review names, lifted verbatim — plain text, never
  // linked (no NCT inference). Empty/absent for study reports.
  discussed_trials?: string[];
  // v0.17 (T6): acronym (normalized) → resolved same-date study slug, for
  // linking the "Trials discussed" list to the auto-resolved card. Mirrored from
  // llm-pipeline.ts — keep in lockstep.
  discussed_trial_links?: Record<string, string>;
  // v0.13: trials watching each open question. Phase 2 emits per-question
  // search queries; the build-time orchestrator hits clinicaltrials.gov per
  // query and reranks across all candidates to pair each pick with the
  // question it answers. Null when Phase 2 abstained, every query failed,
  // or the rerank produced 0 valid picks. Older artifacts won't have this;
  // renderers fall back to no nested trials.
  related_trials?: RelatedTrial[] | null;
  // v0.13: auditable provenance for the trial fetch + rerank pass. Not
  // rendered on the card; ships in /api/v1/*.json for downstream consumers
  // and post-hoc audit. Null when no fetch was attempted.
  related_trials_provenance?: RelatedTrialsProvenance | null;
};

// v0.13: CT.gov status subset we surface as "open to enrollment or
// active follow-up." See plan D8.
export type RelatedTrialStatus =
  | 'RECRUITING'
  | 'NOT_YET_RECRUITING'
  | 'ACTIVE_NOT_RECRUITING'
  | 'ENROLLING_BY_INVITATION';

export const RELATED_TRIAL_STATUSES: readonly RelatedTrialStatus[] = [
  'RECRUITING',
  'NOT_YET_RECRUITING',
  'ACTIVE_NOT_RECRUITING',
  'ENROLLING_BY_INVITATION',
] as const;

// v0.13: Pre-rerank candidate shape. Returned by the CT.gov client; cached
// in-run; fed to the rerank LLM. NOT persisted in the artifact directly;
// only the post-rerank RelatedTrial subset survives.
export type CandidateTrial = {
  nct: string;
  brief_title: string;
  overall_status: RelatedTrialStatus;
  // CT.gov returns Phase as an array; can hold multiple values
  // (e.g. ["PHASE1","PHASE2"]) or be absent for non-interventional studies.
  phase: string[] | null;
  // CT.gov EnrollmentCount: current count if recorded, may be the target on
  // a not-yet-recruiting study. Nullable per the codex #11 note that this
  // is not strictly a contracted target.
  enrollment_count: number | null;
  // YYYY-MM trimmed from CT.gov PrimaryCompletionDate.
  primary_completion_date: string | null;
  // ~500 chars of CT.gov BriefSummary. Gives the rerank LLM real content
  // to judge fit (codex round-2 #3); ground truth for relevance_phrase.
  brief_summary: string | null;
  // CT.gov Conditions array.
  conditions: string[];
  // CT.gov Interventions, normalized to { name, type } pairs.
  interventions: Array<{ name: string; type: string }>;
  // First ~300 chars of CT.gov EligibilityCriteria; lets the rerank judge
  // biomarker / line-of-therapy / population fit.
  eligibility_brief: string | null;
};

// v0.13: Post-rerank shape. Paired to a specific open question on the
// study via byte-identical match against study.open_questions[i].
// What we attach to the study and ship in the artifact.
export type RelatedTrial = CandidateTrial & {
  // EXACT string from study.open_questions. Enforced by parser invariant.
  answers_question: string;
  // ≤ 60 chars. LLM-written tie of this trial to the watched question,
  // grounded in observable candidate fields (BriefSummary / Eligibility /
  // Interventions). VOICE.md compliance enforced via the shared cache block.
  relevance_phrase: string;
};

// v0.13: Auditable provenance (codex round-2 #36). Records what was
// queried, what failed, and the rerank outcome. Not rendered.
export type RelatedTrialsProvenance = {
  queries_fired: string[];
  queries_failed: Array<{ term: string; reason: string }>;
  candidates_returned: number;
  fetched_at: string; // ISO 8601 timestamp
  rerank_outcome: 'picked_N' | 'abstained' | 'failed' | 'skipped' | 'fallback' | 'pinned_by_curator';
};

export type ConsortArm = {
  label: string;
  allocated: number;
  analyzed?: number | null;
};

export type ConsortDiagram = {
  enrolled?: number | null;
  excluded?: number | null;
  randomized: number;
  arms: ConsortArm[];
};

export type SocImplication =
  | 'practice-changing'
  | 'challenges-soc'
  | 'confirmatory'
  | 'early-signal'
  | 'methodologically-limited'
  | 'unclear';

export type StudyVerdict = {
  soc_implication: SocImplication;
  rationale: string;
  audience: string | null;
};

// Normalize a study's figures across schema versions. v0.10 artifacts carry
// `figures[]`; v0.4–v0.9 artifacts carry a single key_figure_url/caption pair.
// Renderers and the Obsidian export read figures exclusively through this so
// both shapes render identically.
export function studyFigures(study: DigestStudy): DigestFigure[] {
  if (study.figures && study.figures.length > 0) return study.figures;
  if (study.key_figure_url) {
    return [{ url: study.key_figure_url, caption: study.key_figure_caption ?? null }];
  }
  return [];
}

// Drop a redundant "NAME:" / "NAME <qualifier>:" label that many TL;DRs lead
// with — the study name is already shown immediately above the TL;DR on every
// card. Conservative: only strips a short label segment that ENDS in a colon (or
// dash), so a name used as a real sentence subject ("PRIME showed …") is left
// intact, and a meaningful qualifier ("20yr", "secondary analysis") is preserved
// as the new lead. Returns the original if stripping would leave too little.
export function stripStudyNamePrefix(tldr: string, name: string): string {
  const t = (tldr ?? '').trim();
  const n = (name ?? '').trim();
  if (!t || !n) return t;
  // Match the name with flexible separators ("PEACE 2" ≈ "PEACE-2"). Trailing
  // tokens are OPTIONAL so an abbreviated restatement still matches — the name
  // "EORTC IM-MS (22922/10925)" is restated as just "EORTC IM-MS 20yr" in the
  // TL;DR (trial numbers dropped, "20yr" qualifier added).
  const toks = n
    .split(/[^a-z0-9]+/i)
    .filter(Boolean)
    .map((tok) => tok.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
  if (toks.length === 0) return t;
  const namePattern =
    toks[0] + toks.slice(1).map((tk) => `(?:[^a-z0-9]+${tk})?`).join('');

  // Case A — plain "NAME: …": strip the full name and its colon. Tried FIRST so
  // a name whose last token abuts the colon ("DBCG RT Natural:") strips whole,
  // instead of Case B mistaking that last token for a qualifier.
  const labelOnly = new RegExp(`^${namePattern}\\s*[:：]\\s*`, 'i');
  const plain = t.replace(labelOnly, '').trim();
  if (plain !== t) return plain.length >= 8 ? plain : t;

  // Case B — "NAME <qualifier>: …": the qualifier ("20yr", "secondary analysis")
  // carries real info, so drop only the name and keep the qualifier as the lead.
  // The 23-char cap + word-char start + required colon keep this to label-style
  // qualifiers, never a full sentence that happens to contain a later colon.
  const withQualifier = new RegExp(`^${namePattern}\\s+([\\w][\\w\\s().\\-]{0,23}?[:：]\\s*)`, 'i');
  const qm = t.match(withQualifier);
  if (qm) {
    const result = `${qm[1]!.trim()} ${t.slice(qm[0].length)}`.trim();
    return result.length >= 8 ? result : t;
  }

  return t;
}

export type DigestArtifactPaper = {
  id: number;
  pmid: string | null;
  doi: string | null;
  pmc_id: string | null;
  title: string;
  authors: string[];
  journal: string | null;
  pub_date: string | null;
  abstract: string | null;
  source_url?: string | null; // v0.15.3: curator-submitted article URL (the link for trade-press papers with no PMID/DOI)
  resolved_from_review?: boolean; // v0.17 (T6): auto-resolved from a review's discussed-trials manifest (curator-approved)
  // fulltext_excerpt_md is intentionally absent from the artifact type: it's
  // not written to data/digests (kept out of git for copyright) and nothing
  // renders it. The build-time LLM reads it from the DB instead.
  pdf_path?: string | null; // v0.8 PR2: local vault path; never rendered on the public site, stripped from the API
  note: string | null;
};

export type DigestArtifactSlide = {
  id: number;
  file_path: string;
  mime_type: string;
  width: number | null;
  height: number | null;
  source_label: string | null;
  ocr_text: string | null;
  note: string | null;
  source_batch_key: string | null;
};

export type DigestSite = {
  disease_site: string;
  intro: string | null;
  studies: DigestStudy[];
  open_questions: string[] | null;
};

// Disclosure: surfaces incompleteness rather than silently omitting. Older
// (v0.3) artifacts don't carry this field; consumers should treat absence
// as "no disclosure data available."
export type DigestMeta = {
  clusters_total: number;
  studies_analyzed: number;
  dropped: Array<{ slug: string; name: string; reason: string }>;
  ocr_available: boolean;
};

export type DigestArtifact = {
  date: string; // YYYY-MM-DD
  conference: { slug: string; name: string } | null;
  generated_at: number;
  digest: {
    top_line: string;
    tldr: string;
    sites: DigestSite[];
    meta?: DigestMeta; // v0.4+
  };
  bookmarks: Array<{
    id: number;
    url: string;
    bookmark_date: string;
    author_handle: string | null;
    author_name: string | null;
    text: string;
    html: string | null;
    image_urls: string[];
    image_ocr_texts?: string[]; // v0.4+, aligned with image_urls
    note: string | null;
    fetched_via: string;
    conference_slug: string | null;
  }>;
  papers?: DigestArtifactPaper[]; // v0.5+
  slides?: DigestArtifactSlide[]; // v0.5+
};

const DIGEST_ROOT = resolve(process.cwd(), 'data/digests');

// Cheap content-change signature of the digests dir: sorted (name, mtime, size)
// triples. Re-parsing every artifact's JSON on every page render is the
// build-time O(pages × files) cliff; caching keyed on this signature skips the
// re-parse while staying correct outside the immutable-Astro-build context
// (build:day / studio write files, and the signature changes when they do).
function digestDirSignature(dir: string): string | null {
  if (!existsSync(dir)) return null;
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return null;
  }
  const parts: string[] = [];
  for (const file of entries) {
    if (!file.endsWith('.json')) continue;
    try {
      const st = statSync(join(dir, file));
      parts.push(`${file}:${st.mtimeMs}:${st.size}`);
    } catch {
      /* file vanished between readdir and stat — skip */
    }
  }
  return parts.sort().join('|');
}

let _listDigestsCache: { sig: string; value: DigestArtifact[] } | null = null;

// Reset the listDigests memo. Tests that mutate data/digests within one process
// and rely on a same-path rewrite (where coarse mtime granularity could miss a
// change) call this to force a fresh read.
export function resetListDigestsCache(): void {
  _listDigestsCache = null;
}

// Returns all digest artifacts, newest first. Flat directory layout:
// data/digests/YYYY-MM-DD.json. Filename matches the artifact's date field.
export function listDigests(): DigestArtifact[] {
  const sig = digestDirSignature(DIGEST_ROOT);
  if (sig === null) return [];
  if (_listDigestsCache && _listDigestsCache.sig === sig) return _listDigestsCache.value;
  const out: DigestArtifact[] = [];
  let entries: string[];
  try {
    entries = readdirSync(DIGEST_ROOT);
  } catch {
    return [];
  }
  for (const file of entries) {
    if (!file.endsWith('.json')) continue;
    try {
      const raw = readFileSync(join(DIGEST_ROOT, file), 'utf-8');
      const parsed = JSON.parse(raw) as DigestArtifact;
      out.push(parsed);
    } catch {
      // Skip malformed files rather than break the entire build.
    }
  }
  const value = out.sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));
  _listDigestsCache = { sig, value };
  return value;
}

export function getDigest(date: string): DigestArtifact | null {
  return listDigests().find((d) => d.date === date) ?? null;
}

export type ConferenceSummary = {
  slug: string;
  name: string;
  dates: string[]; // YYYY-MM-DD, newest first
};

// Aggregation by disease site: every study from every digest that's tagged with
// the given site, newest first. Used by /sites/[site]/ pages.
export type SiteStudyOccurrence = {
  date: string; // YYYY-MM-DD
  conference: { slug: string; name: string } | null;
  study: DigestStudy;
  // v0.10: per-date resolved slug (matches the anchor on /<date>/ page). Used
  // by callers that look up cross-axis data keyed by {date, resolvedSlug} —
  // notably the v0.10 sibling map. Computed via assignSlugsForDate over the
  // FULL per-date study list (across all disease-site sections), so two
  // same-name studies in different sections get the same -2/-3 suffix
  // resolution as the date page.
  resolvedSlug: string;
  bookmarks: DigestArtifact['bookmarks']; // bookmarks referenced by this study
  papers?: DigestArtifactPaper[]; // v0.5+: papers referenced by this study
  slides?: DigestArtifactSlide[]; // v0.5+: slides referenced by this study
};

export type SiteSummary = {
  disease_site: string;
  occurrences: SiteStudyOccurrence[];
};

export function listSiteSummaries(): SiteSummary[] {
  const bySite = new Map<string, SiteStudyOccurrence[]>();
  for (const artifact of listDigests()) {
    const bookmarkById = new Map(artifact.bookmarks.map((b) => [b.id, b]));
    const papersById = new Map((artifact.papers ?? []).map((p) => [p.id, p]));
    const slidesById = new Map((artifact.slides ?? []).map((s) => [s.id, s]));
    // v0.10: compute per-date resolved slugs across ALL disease-site sections,
    // matching tag-index.ts:walkStudiesPerDate. Indexed positionally by the
    // flat study list, then mapped back to each (site, study) pair below.
    const allStudiesOnDate = artifact.digest.sites.flatMap((s) => s.studies);
    const resolvedSlugs = assignSlugsForDate(allStudiesOnDate);
    let perDateIdx = 0;
    for (const site of artifact.digest.sites) {
      if (!bySite.has(site.disease_site)) bySite.set(site.disease_site, []);
      const list = bySite.get(site.disease_site)!;
      for (const study of site.studies) {
        const resolvedSlug = resolvedSlugs[perDateIdx++]!;
        // v0.5: typed refs preferred; tweet_ids is the back-compat fallback.
        const refs: DigestSourceRef[] = study.source_ids ?? study.tweet_ids.map((id) => ({ type: 'tweet' as const, id }));
        const studyBookmarks = refs
          .filter((r) => r.type === 'tweet')
          .map((r) => bookmarkById.get(r.id))
          .filter((b): b is NonNullable<typeof b> => Boolean(b));
        const studyPapers = refs
          .filter((r) => r.type === 'paper')
          .map((r) => papersById.get(r.id))
          .filter((p): p is DigestArtifactPaper => Boolean(p));
        const studySlides = refs
          .filter((r) => r.type === 'slide')
          .map((r) => slidesById.get(r.id))
          .filter((s): s is DigestArtifactSlide => Boolean(s));
        list.push({
          date: artifact.date,
          conference: artifact.conference,
          study,
          resolvedSlug,
          bookmarks: studyBookmarks,
          papers: studyPapers.length > 0 ? studyPapers : undefined,
          slides: studySlides.length > 0 ? studySlides : undefined,
        });
      }
    }
  }
  return Array.from(bySite.entries()).map(([disease_site, occurrences]) => ({
    disease_site,
    occurrences: occurrences.sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0)),
  }));
}

// v0.21: one entry per study, the data behind the standalone /study/{param}/
// page + its /og/study/{param}.png card. `param` is `${date}-${resolvedSlug}`,
// which is the SAME date-prefixed key the date page + site page use as an
// in-page anchor and is globally unique (assignSlugsForDate disambiguates every
// study on a date, so no two studies share it). The standalone page is what a
// SHARED study link unfurls to — a URL fragment (the old `/sites/{site}/#anchor`
// share target) is invisible to link unfurlers, so they fell back to the
// site-level OG card; a real page gives the study its own og:title + og:image.
export type StudyPageEntry = {
  param: string;
  date: string;
  conference: DigestArtifact['conference'];
  disease_site: string;
  study: DigestStudy;
  resolvedSlug: string;
  bookmarks: DigestArtifact['bookmarks'];
  papers: DigestArtifactPaper[];
  slides: DigestArtifactSlide[];
};

export function listStudyPages(): StudyPageEntry[] {
  const out: StudyPageEntry[] = [];
  for (const summary of listSiteSummaries()) {
    for (const occ of summary.occurrences) {
      out.push({
        param: `${occ.date}-${occ.resolvedSlug}`,
        date: occ.date,
        conference: occ.conference,
        disease_site: summary.disease_site,
        study: occ.study,
        resolvedSlug: occ.resolvedSlug,
        bookmarks: occ.bookmarks,
        papers: occ.papers ?? [],
        slides: occ.slides ?? [],
      });
    }
  }
  return out;
}

export type RecentStudy = {
  date: string;
  conference: DigestArtifact['conference'];
  disease_site: string;
  study: DigestStudy;
  // Per-date resolved slug (matches the anchor id on [date].astro). Always
  // populated — falls back to deriveSlug(name) for old artifacts and
  // suffixes -2/-3 for same-day collisions, exactly like the search index.
  slug: string;
};

// Flat list of recently-added studies across all dates. Used by the homepage
// hero strip so a returning reader sees the last N study additions, not a
// list of dates. Iterates listDigests() (date-desc) and emits in render order
// within each date; assignSlugsForDate() makes the slugs match the [date]
// page anchors so /<date>/#<slug> deep-links resolve correctly.
export function listRecentStudies(limit: number): RecentStudy[] {
  const out: RecentStudy[] = [];
  for (const artifact of listDigests()) {
    const allStudiesOnDate = artifact.digest.sites.flatMap((s) => s.studies);
    const slugs = assignSlugsForDate(allStudiesOnDate);
    let i = 0;
    for (const site of artifact.digest.sites) {
      for (const study of site.studies) {
        out.push({
          date: artifact.date,
          conference: artifact.conference,
          disease_site: site.disease_site,
          study,
          slug: slugs[i++]!,
        });
        if (out.length >= limit) return out;
      }
    }
  }
  return out;
}

// Groups all conference-tagged digests by their conference slug.
// Used for the conference index pages and for the homepage badges.
export function listConferenceSummaries(): ConferenceSummary[] {
  const byConf = new Map<string, ConferenceSummary>();
  for (const a of listDigests()) {
    if (!a.conference) continue;
    const key = a.conference.slug;
    if (!byConf.has(key)) {
      byConf.set(key, { slug: key, name: a.conference.name, dates: [] });
    }
    byConf.get(key)!.dates.push(a.date);
  }
  return Array.from(byConf.values()).map((c) => ({
    ...c,
    dates: c.dates.sort((a, b) => (a < b ? 1 : -1)),
  }));
}
