domains:
- domain: oncbrain.oncologytoolkit.com
  type: PRIMARY
  zone: oncologytoolkit.com
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: web
    match:
      path:
        prefix: /
name: oncbrain
region: sfo
static_sites:
- build_command: npm run build
  catchall_document: index.html
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: nb2276/oncbrain
  name: web
  output_dir: dist
  source_dir: /
